
export const services = [
  // Semiconductors
  {
    id: 'analog-and-mixed-signal',
    category: 'Semiconductors',
    title: 'Analog and Mixed-Signal IC Design',
    description: 'We specialize in creating high-performance Analog and Mixed-Signal Integrated Circuits (ICs) that bridge the physical and digital worlds, enabling seamless interaction and superior performance for your most complex applications.',
    imageId: 'service-1',
    href: '/services/analog-and-mixed-signal',
  },
  {
    id: 'ate',
    category: 'Semiconductors',
    title: 'ATE Program Development',
    description: 'We provide comprehensive Automated Test Equipment (ATE) program development services to ensure your semiconductor devices are tested efficiently, accurately, and cost-effectively from characterization to high-volume production.',
    imageId: 'service-2',
    href: '/services/ate',
  },
  {
    id: 'bench-characterization',
    category: 'Semiconductors',
    title: 'Bench Characterization',
    description: 'We offer comprehensive bench characterization services to validate your silicon, providing the in-depth performance data needed to ensure your device meets and exceeds specifications before production.',
    imageId: 'service-3',
    href: '/services/bench-characterization',
  },
  {
    id: 'design-verification',
    category: 'Semiconductors',
    title: 'Design Verification',
    description: 'Our rigorous design verification methodologies ensure your digital and mixed-signal designs are bug-free and functionally correct, mitigating risk and preventing costly silicon respins.',
    imageId: 'service-4',
    href: '/services/design-verification',
  },
  {
    id: 'dft',
    category: 'Semiconductors',
    title: 'Design for Test (DFT)',
    description: 'We integrate comprehensive Design for Test (DFT) methodologies into your ASIC design flow to ensure high-quality manufacturing tests, improved yield, and reduced test costs.',
    imageId: 'product-1',
    href: '/services/dft',
  },
  {
    id: 'fpga-design',
    category: 'Semiconductors',
    title: 'FPGA Design',
    description: 'We offer comprehensive FPGA design services, from concept to deployed solution, providing the flexibility and performance you need for prototyping, low-volume production, and acceleration.',
    imageId: 'product-2',
    href: '/services/fpga-design',
  },
  {
    id: 'in-house-silicon-validation-lab',
    category: 'Semiconductors',
    title: 'In-House Silicon Validation Lab',
    description: 'Our state-of-the-art in-house lab provides the critical infrastructure for comprehensive silicon bring-up, validation, and characterization, ensuring your product is robust and market-ready.',
    imageId: 'product-3',
    href: '/services/in-house-silicon-validation-lab',
  },
  {
    id: 'physical-design',
    category: 'Semiconductors',
    title: 'Physical Design',
    description: 'We provide end-to-end physical design services, transforming your synthesized netlist into a production-ready GDSII layout, optimized for power, performance, and area (PPA).',
    imageId: 'product-4',
    href: '/services/physical-design',
  },
  {
    id: 'prototyping-and-emulation',
    category: 'Semiconductors',
    title: 'Prototyping and Emulation',
    description: 'Accelerate your software development and system-level validation with our advanced FPGA-based prototyping and emulation services, enabling early bug detection and massive verification speed-up.',
    imageId: 'product-5',
    href: '/services/prototyping-and-emulation',
  },

  // Embedded
  {
    id: 'bare-metal-programming',
    category: 'Embedded',
    title: 'Bare Metal Programming',
    description: 'We deliver highly optimized, lightweight, and real-time capable firmware through expert bare metal programming, directly controlling hardware for maximum performance and minimum overhead.',
    imageId: 'product-6',
    href: '/services/bare-metal-programming',
  },
  {
    id: 'board-support-package',
    category: 'Embedded',
    title: 'Board Support Package (BSP) Development',
    description: 'We create robust, production-quality Board Support Packages (BSPs) that abstract your custom hardware, enabling your application developers to work with a standardized, portable API.',
    imageId: 'service-1',
    href: '/services/board-support-package',
  },
  {
    id: 'ci-cd',
    category: 'Embedded',
    title: 'CI/CD for Embedded Systems',
    description: 'We implement modern Continuous Integration and Continuous Deployment (CI/CD) pipelines tailored for the unique challenges of embedded systems development, increasing quality and accelerating your development lifecycle.',
    imageId: 'service-2',
    href: '/services/ci-cd',
  },
  {
    id: 'device-drivers',
    category: 'Embedded',
    title: 'Device Driver Development',
    description: 'We develop high-quality, reliable, and performant device drivers for any OS, enabling your custom hardware and peripherals to function seamlessly with your system.',
    imageId: 'service-3',
    href: '/services/device-drivers',
  },
  {
    id: 'diagnostics',
    category: 'Embedded',
    title: 'Embedded Diagnostics',
    description: 'We develop comprehensive diagnostic software that runs on your hardware, enabling rapid testing, fault detection, and failure analysis in manufacturing, service, and development environments.',
    imageId: 'service-4',
    href: '/services/diagnostics',
  },
  {
    id: 'os-porting-and-customization',
    category: 'Embedded',
    title: 'OS Porting and Customization',
    description: 'We adapt and optimize your chosen operating system—from Linux and Android to real-time operating systems (RTOS)—to run flawlessly on your custom hardware.',
    imageId: 'product-1',
    href: '/services/os-porting-and-customization',
  },
  {
    id: 'cyber-security',
    category: 'Embedded',
    title: 'Embedded Cyber Security',
    description: 'We help you build secure embedded systems from the ground up, protecting your devices, your data, and your customers from emerging threats.',
    imageId: 'product-2',
    href: '/services/cyber-security',
  },
  {
    id: 'verification-and-validation',
    category: 'Embedded',
    title: 'Verification and Validation (V&V)',
    description: 'Our independent Verification and Validation (V&V) services provide a systematic and rigorous approach to ensure your embedded system meets its technical and business requirements, delivering quality and reliability.',
    imageId: 'product-3',
    href: '/services/verification-and-validation',
  },

  // Software
  {
    id: 'data-analytics-ai-and-machine-learning',
    category: 'Software',
    title: 'Data Analytics, AI and Machine Learning',
    description: 'We help you harness the power of your data, leveraging advanced analytics, artificial intelligence (AI), and machine learning (ML) to unlock actionable insights, automate processes, and create intelligent products.',
    imageId: 'product-4',
    href: '/services/data-analytics-ai-and-machine-learning',
  },
  {
    id: 'cloud-architecture-and-engineering',
    category: 'Software',
    title: 'Cloud Architecture and Engineering',
    description: 'We design and build scalable, secure, and resilient cloud infrastructure on AWS, Google Cloud, and Azure, enabling you to innovate faster and operate more efficiently.',
    imageId: 'product-5',
    href: '/services/cloud-architecture-and-engineering',
  },
  {
    id: 'salesforce-implementation-and-support',
    category: 'Software',
    title: 'Salesforce Implementation and Support',
    description: 'We help you unlock the full potential of the Salesforce platform with expert implementation, customization, and ongoing support services tailored to your business needs.',
    imageId: 'product-6',
    href: '/services/salesforce-implementation-and-support',
  },
  {
    id: 'application-development-and-maintenance',
    category: 'Software',
    title: 'Application Development and Maintenance',
    description: 'We provide end-to-end application development services to build, deploy, and maintain robust, scalable, and secure software solutions that meet your business objectives.',
    imageId: 'service-1',
    href: '/services/application-development-and-maintenance',
  },
  {
    id: 'quality-assurance',
    category: 'Software',
    title: 'Quality Assurance',
    description: 'Our comprehensive Quality Assurance (QA) and testing services ensure that your software is reliable, functional, secure, and delivers an excellent user experience.',
    imageId: 'service-2',
    href: '/services/quality-assurance',
  },
  {
    id: 'it-infrastructure',
    category: 'Software',
    title: 'IT Infrastructure Management',
    description: 'We provide comprehensive IT infrastructure services, from design and implementation to ongoing management and support, ensuring your core technology is reliable, secure, and aligned with your business goals.',
    imageId: 'service-3',
    href: '/services/it-infrastructure',
  },
  {
    id: 'engineering-and-technical-services',
    category: 'Software',
    title: 'Engineering and Technical Services',
    description: 'We provide specialized engineering and technical services to support your entire product lifecycle, augmenting your team with the expertise you need, when you need it.',
    imageId: 'service-4',
    href: '/services/engineering-and-technical-services',
  }
];

export const products = [
  {
    id: 1,
    name: 'QuantumCore Q-1 Processor',
    specs: ['7nm Process Technology', '128-bit Architecture', 'AI Acceleration Engine', 'Ultra-Low Power Consumption'],
    brochureUrl: '/brochures/product1.pdf',
    imageId: 'product-1',
  },
  {
    id: 2,
    name: 'NeuroLink N-1 Neural Engine',
    specs: ['Dedicated AI/ML SoC', 'High-Performance Inference', 'Scalable for Edge Devices', 'Comprehensive SDK'],
    brochureUrl: '/brochures/product2.pdf',
    imageId: 'product-2',
  },
  {
    id: 3,
    name: 'PhotonX P-1 Optical Transceiver',
    specs: ['400Gbps Data Rate', 'Silicon Photonics Technology', 'Low Latency for HPC', 'Compact Form Factor'],
    brochureUrl: '/brochures/product3.pdf',
    imageId: 'product-3',
  },
  {
    id: 4,
    name: 'EcoWatt E-1 Power Management IC',
    specs: ['98% Power Efficiency', 'Dynamic Voltage Scaling', 'Integrated Battery Charger', 'Automotive Grade'],
    brochureUrl: '/brochures/product4.pdf',
    imageId: 'product-4',
  },
  {
    id: 5,
    name: 'SensorFusion S-1 IoT Hub',
    specs: ['Multi-protocol Wireless', 'On-chip Security Core', 'Integrated Sensor Interface', 'Low-power Standby Modes'],
    brochureUrl: '/brochures/product5.pdf',
    imageId: 'product-5',
  },
  {
    id: 6,
    name: 'CryoMem C-1 Quantum Memory',
    specs: ['For Quantum Computing', 'High-Fidelity Qubits', 'Cryogenic Operation', 'Scalable Architecture'],
    brochureUrl: '/brochures/product6.pdf',
    imageId: 'product-6',
  },
];
    
